name: marp-to-pages
concurrency: marp-to-pages

env:
  MARP_CLI_VERSION: 4.3.1

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
            npm install -g @marp-team/marp-cli@${{ env.MARP_CLI_VERSION }}
            marp --theme themes/aqua.css presentation.md -o ./public/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
